const defaults={debtMax:"60",cashMin:"100",reserveMin:"1",bookMin:"5"};let rawCache=null,currentRows=[];const $=id=>document.getElementById(id);const fmt=(v,d=2)=>new Intl.NumberFormat("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
function quoteUrl(page,attempt=0){const p=new URLSearchParams({pn:String(page),pz:"100",po:"0",np:"1",fltt:"2",invt:"2",fid:"f12",fs:"m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23,m:0+t:81+s:2048",fields:"f2,f3,f12,f14,f57,f61,f100,f113,f124"});const host=attempt===0?"push2.eastmoney.com":`${((page+attempt*31)%90)+10}.push2.eastmoney.com`;return `https://${host}/api/qt/clist/get?${p}`}
async function quotePage(page){for(let a=0;a<3;a++){try{const r=await fetch(quoteUrl(page,a));if(!r.ok)continue;const j=await r.json();if(j.data?.diff)return j}catch{}}throw new Error(`瀹炴椂琛屾儏绗?${page} 椤垫殏鏃舵棤娉曡幏鍙朻)}
async function loadMarket(){if(rawCache)return rawCache;const financePromise=fetch("./data/financials.json").then(async r=>{if(!r.ok)throw new Error("璐㈡姤鏁版嵁鏂囦欢鏆傛椂涓嶅彲鐢?);return r.json()});const first=await quotePage(1);const pages=Array.from({length:Math.max(0,Math.ceil((first.data?.total||0)/100)-1)},(_,i)=>i+2);const payloads=[];for(let i=0;i<pages.length;i+=6)payloads.push(...await Promise.all(pages.slice(i,i+6).map(quotePage)));const rows=[...(first.data?.diff||[]),...payloads.flatMap(x=>x.data?.diff||[])];const finance=await financePromise;rawCache={quotes:[...new Map(rows.map(x=>[x.f12,x])).values()],...finance};return rawCache}
function params(){return Object.fromEntries(Object.keys(defaults).map(k=>[k,$(k).value]))}function setParams(v){for(const k of Object.keys(defaults))$(k).value=v[k]??defaults[k]}
function loading(on){$("screen-button").disabled=on;$("screen-button").querySelector("span").textContent=on?"姝ｅ湪杩炴帴甯傚満鏁版嵁鈥?:"寮€濮嬮€夎偂";if(on){$("result-title").textContent="绛涢€変腑";$("status").innerHTML='<div class="loading-list">'+"<span></span>".repeat(5)+"</div>";$("table-wrap").hidden=true}}
async function run(){loading(true);try{const m=await loadMarket(),v=params(),f=new Map(m.financials.map(x=>[x.code,x]));const matched=m.quotes.flatMap(q=>{const r=f.get(q.f12);if(!r||r.eps==null||r.operatingCashPerShare==null||r.eps<=0)return[];const cash=r.operatingCashPerShare/r.eps*100;if(![q.f2,q.f3,q.f57,q.f61,q.f113,cash].every(Number.isFinite))return[];if(!(q.f57<+v.debtMax&&cash>+v.cashMin&&q.f61>+v.reserveMin&&q.f113>+v.bookMin))return[];return[{code:q.f12,name:q.f14,price:q.f2,change:q.f3,industry:q.f100||"",debtRatio:q.f57,cashContent:cash,capitalReserve:q.f61,bookValue:q.f113}]}).sort((a,b)=>b.cashContent-a.cashContent);currentRows=matched.slice(0,500);const ts=Math.max(...m.quotes.map(q=>q.f124||0)),qt=ts?new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(ts*1000)):"鏈€杩戜氦鏄撴椂鐐?;$("result-title").textContent=`${matched.length} 瀹剁鍚堟潯浠禶;$("result-meta").textContent=`宸叉壂鎻?${m.quotes.length} 瀹?路 璐㈡姤 ${m.reportDate} 路 琛屾儏 ${qt}`;$("status").innerHTML="";if(currentRows.length){$("results-body").innerHTML=currentRows.map(s=>`<tr><td><strong>${s.name}</strong><span>${s.code} 路 ${s.industry||"鏈垎绫?}</span></td><td>楼 ${fmt(s.price)}</td><td class="${s.change>=0?"up":"down"}">${s.change>=0?"+":""}${fmt(s.change)}%</td><td>${fmt(s.debtRatio)}%</td><td><b class="cash-value">${fmt(s.cashContent,1)}%</b></td><td>楼 ${fmt(s.capitalReserve)}</td><td>楼 ${fmt(s.bookValue)}</td></tr>`).join("");$("table-wrap").hidden=false;$("limit-note").hidden=matched.length<=500}else{$("status").innerHTML='<div class="empty-state"><b>0</b><strong>鏆傛椂娌℃湁鑲＄エ鍚屾椂婊¤冻鍥涢」鏉′欢</strong><p>鍙互閫傚綋鏀惧鍏朵腑涓€椤癸紝鍐嶆绛涢€夈€?/p></div>'}$("export").disabled=!currentRows.length;history.replaceState(null,"","?"+new URLSearchParams(v))}catch(e){$("result-title").textContent="鏈兘瀹屾垚绛涢€?;$("status").innerHTML=`<div class="error-box"><strong>鍦ㄧ嚎鏁版嵁鏆傛椂涓嶅彲鐢?/strong><span>${e.message}</span></div>`}finally{loading(false)}}
$("screen-form").addEventListener("submit",e=>{e.preventDefault();run()});$("reset").addEventListener("click",()=>setParams(defaults));$("copy-link").addEventListener("click",async()=>{await navigator.clipboard.writeText(location.href);$("copy-link").textContent="宸插鍒?;setTimeout(()=>$("copy-link").textContent="澶嶅埗鏉′欢閾炬帴",1600)});$("export").addEventListener("click",()=>{const h=["鑲＄エ浠ｇ爜","鑲＄エ鍚嶇О","鏈€鏂颁环","娑ㄨ穼骞?,"琛屼笟","璧勪骇璐熷€虹巼","鍑€鍒╂鼎鐜伴噾鍚噺","姣忚偂璧勬湰鍏Н","姣忚偂鍑€璧勪骇"],rows=currentRows.map(s=>[s.code,s.name,s.price,s.change,s.industry,s.debtRatio,s.cashContent,s.capitalReserve,s.bookValue]),csv="\uFEFF"+[h,...rows].map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download=`鍥涙柟鏉ヨ储-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(u)});setParams({...defaults,...Object.fromEntries(new URLSearchParams(location.search))});run();

