const defaults={debtMax:"60",cashMin:"100",reserveMin:"1",bookMin:"5"};let rawCache=null,currentRows=[];const $=id=>document.getElementById(id);const fmt=(v,d=2)=>new Intl.NumberFormat("zh-CN",{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
function quoteUrl(page,attempt=0){const p=new URLSearchParams({pn:String(page),pz:"100",po:"0",np:"1",fltt:"2",invt:"2",fid:"f12",fs:"m:0+t:6,m:0+t:80,m:1+t:2,m:1+t:23,m:0+t:81+s:2048",fields:"f2,f3,f12,f14,f57,f61,f100,f113,f124"});const host=attempt===0?"push2.eastmoney.com":`${((page+attempt*31)%90)+10}.push2.eastmoney.com`;return `https://${host}/api/qt/clist/get?${p}`}
async function quotePage(page){for(let a=0;a<3;a++){try{const r=await fetch(quoteUrl(page,a));if(!r.ok)continue;const j=await r.json();if(j.data?.diff)return j}catch{}}throw new Error(`实时行情第 ${page} 页暂时无法获取`)}
async function loadMarket(){if(rawCache)return rawCache;const financePromise=fetch("./data/financials.json").then(async r=>{if(!r.ok)throw new Error("财报数据文件暂时不可用");return r.json()});const first=await quotePage(1);const pages=Array.from({length:Math.max(0,Math.ceil((first.data?.total||0)/100)-1)},(_,i)=>i+2);const payloads=[];for(let i=0;i<pages.length;i+=6)payloads.push(...await Promise.all(pages.slice(i,i+6).map(quotePage)));const rows=[...(first.data?.diff||[]),...payloads.flatMap(x=>x.data?.diff||[])];const finance=await financePromise;rawCache={quotes:[...new Map(rows.map(x=>[x.f12,x])).values()],...finance};return rawCache}
function params(){return Object.fromEntries(Object.keys(defaults).map(k=>[k,$(k).value]))}function setParams(v){for(const k of Object.keys(defaults))$(k).value=v[k]??defaults[k]}
function loading(on){$("screen-button").disabled=on;$("screen-button").querySelector("span").textContent=on?"正在连接市场数据…":"开始选股";if(on){$("result-title").textContent="筛选中";$("status").innerHTML='<div class="loading-list">'+"<span></span>".repeat(5)+"</div>";$("table-wrap").hidden=true}}
async function run(){loading(true);try{const m=await loadMarket(),v=params(),f=new Map(m.financials.map(x=>[x.code,x]));const matched=m.quotes.flatMap(q=>{const r=f.get(q.f12);if(!r||r.eps==null||r.operatingCashPerShare==null||r.eps<=0)return[];const cash=r.operatingCashPerShare/r.eps*100;if(![q.f2,q.f3,q.f57,q.f61,q.f113,cash].every(Number.isFinite))return[];if(!(q.f57<+v.debtMax&&cash>+v.cashMin&&q.f61>+v.reserveMin&&q.f113>+v.bookMin))return[];return[{code:q.f12,name:q.f14,price:q.f2,change:q.f3,industry:q.f100||"",debtRatio:q.f57,cashContent:cash,capitalReserve:q.f61,bookValue:q.f113}]}).sort((a,b)=>b.cashContent-a.cashContent);currentRows=matched.slice(0,500);const ts=Math.max(...m.quotes.map(q=>q.f124||0)),qt=ts?new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(ts*1000)):"最近交易时点";$("result-title").textContent=`${matched.length} 家符合条件`;$("result-meta").textContent=`已扫描 ${m.quotes.length} 家 · 财报 ${m.reportDate} · 行情 ${qt}`;$("status").innerHTML="";if(currentRows.length){$("results-body").innerHTML=currentRows.map(s=>`<tr><td><strong>${s.name}</strong><span>${s.code} · ${s.industry||"未分类"}</span></td><td>¥ ${fmt(s.price)}</td><td class="${s.change>=0?"up":"down"}">${s.change>=0?"+":""}${fmt(s.change)}%</td><td>${fmt(s.debtRatio)}%</td><td><b class="cash-value">${fmt(s.cashContent,1)}%</b></td><td>¥ ${fmt(s.capitalReserve)}</td><td>¥ ${fmt(s.bookValue)}</td></tr>`).join("");$("table-wrap").hidden=false;$("limit-note").hidden=matched.length<=500}else{$("status").innerHTML='<div class="empty-state"><b>0</b><strong>暂时没有股票同时满足四项条件</strong><p>可以适当放宽其中一项，再次筛选。</p></div>'}$("export").disabled=!currentRows.length;history.replaceState(null,"","?"+new URLSearchParams(v))}catch(e){$("result-title").textContent="未能完成筛选";$("status").innerHTML=`<div class="error-box"><strong>在线数据暂时不可用</strong><span>${e.message}</span></div>`}finally{loading(false)}}
$("screen-form").addEventListener("submit",e=>{e.preventDefault();run()});$("reset").addEventListener("click",()=>setParams(defaults));$("copy-link").addEventListener("click",async()=>{await navigator.clipboard.writeText(location.href);$("copy-link").textContent="已复制";setTimeout(()=>$("copy-link").textContent="复制条件链接",1600)});$("export").addEventListener("click",()=>{const h=["股票代码","股票名称","最新价","涨跌幅","行业","资产负债率","净利润现金含量","每股资本公积","每股净资产"],rows=currentRows.map(s=>[s.code,s.name,s.price,s.change,s.industry,s.debtRatio,s.cashContent,s.capitalReserve,s.bookValue]),csv="\uFEFF"+[h,...rows].map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download=`四方来财-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(u)});setParams({...defaults,...Object.fromEntries(new URLSearchParams(location.search))});run();

